name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn build --if-present
    - run: yarn pack
